Moved code to a different branch
TheXGeneral/Wolpack_A1 pull request #3
Opened 2021-04-12 07:16 UTC by TheXGeneral

2021-04-12 07:30 UTC, AdrianFlorian requested changes
Nice job 👏

Overall comments: 
- watch out for the spacing
- please rename the PR (pull request) name to reflect the functionality + update the description of the PR
- naming conventions are important
- avoid duplicated code as much as possible :-)

2021-04-12 07:30 UTC, AdrianFlorian commented on css/rSlider.min.css
> +}
please keep the spacing and new lines consistent :-)

2021-04-12 07:30 UTC, AdrianFlorian commented on js/data.js
> +    {id:uuidv4(),photo_link:"img/food.jpg",name:"Pasta Carbonara",category:"Second courses",price:2},
spacing :-), space after `,` please

2021-04-12 07:30 UTC, AdrianFlorian commented on js/edit.js
> +}
same here new line :-)

2021-04-12 07:30 UTC, AdrianFlorian commented on js/edit.js
> +function open_edit_menu(){
function names in JS have camel case `openEditMenu`

2021-04-12 07:30 UTC, AdrianFlorian commented on js/edit.js
> +    Data[position_to_update]["price"]=new_price;
why not put this in a new variable? `Data[position_to_update]` this way you will not have to duplicate the code :-)

2021-04-12 13:32 UTC, TheXGeneral commented on js/edit.js
> +function open_edit_menu(){
Now, all functions in Js use camelCase and all classes in CSS use kebab-case

2021-04-12 13:32 UTC, TheXGeneral commented on js/data.js
> +    {id:uuidv4(),photo_link:"img/food.jpg",name:"Pasta Carbonara",category:"Second courses",price:2},
I added space after every comma and before and after every =, ==, etc.

2021-04-13 07:09 UTC, AdrianFlorian requested changes
Nice job Dan, almost there!

Please watch out for the comments, a good code should never need comments.

Also, please add a descriptive title to the PR and a good description. Check https://github.com/cristichirtos/RoR-internship-assignment-1/pull/1 as an inspiration :-)

2021-04-13 07:09 UTC, AdrianFlorian commented on js/data.js
> +//import Item from "./domain.js";
why the comment? :-)

2021-04-13 07:09 UTC, AdrianFlorian commented on js/edit.js
> +//CRUD
no need to have unnecessary comments

2021-04-13 07:09 UTC, AdrianFlorian commented on js/edit.js
> +//loading data into the menu
If you feel the need to add a comment above a method name it means that it's name is not descriptive enough. You 
If you ever need to add comments inside a method, it means it's trying to do too much and it needs to be broken down into multiple smaller methods with descriptive names. 🤘

2021-04-13 07:09 UTC, AdrianFlorian commented on js/index.js
> +    //TODO implement set raange limits function
remove comment

2021-04-13 07:26 UTC, chioreandan requested changes
I forgot to submit the review. Some comments might not be applicable

2021-04-13 17:48 UTC, chioreandan commented on js/edit.js
> +    for(let i = 1; i < columns.length-1; i++){
use ``` forEach() ```

2021-04-15 06:03 UTC, chioreandan commented on index.html
> +<!DOCTYPE html>
Change your tab spacing to 2 instead of 4

2021-04-15 09:42 UTC, AdrianFlorian approved these changes
@TheXGeneral nice job!  👏

2021-04-15 09:42 UTC, AdrianFlorian commented on css/index.css
> +/*scrollbar*/
do you need this comment? :-)

2021-04-26 07:05 UTC, chioreandan approved these changes
Nice job @TheXGeneral 👍. Please also check the conflicts that you have.

2021-04-26 07:18 UTC, merged